### ISSUE TITLE
add possibility to get comment of the worklog

### ISSUE THREAD

**Issue by makarova** [everit-org/jira-worklog-query-plugin#8]
add more data to json response: first of all the comment of the worklog

**Comment by balazs-zsoldos** [comment]
Comments were left out due to the reason that the original goal of the plugin was to
- Query large amount of data from google docs or other client
- Create statistics and diagrams about the state of the projects

If comments are included in the response, it can make the response too large in some cases.

I can imagine an additional parameter that allows to put comments into the response.

**Comment by makarova** [comment]
There are may be optional params which will or will not appear in the response. This can make the plugin more convenient for users.

**Comment by balazs-zsoldos** [comment]
Done in version 1.2.0
